//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  context: Context;
  contextConnection: ContextConnection;
  pipeline: Pipeline;
  pipelineConnection: PipelineConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContextArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContextConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContextFilter>;
};


export type QueryPipelineArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPipelineConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PipelineFilter>;
};

export type DocumentFilter = {
  context?: InputMaybe<ContextFilter>;
  pipeline?: InputMaybe<PipelineFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Context | Pipeline | Folder;

export type Context = Node & Document & {
  __typename?: 'Context';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ContextFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ContextConnectionEdges = {
  __typename?: 'ContextConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Context>;
};

export type ContextConnection = Connection & {
  __typename?: 'ContextConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContextConnectionEdges>>>;
};

export type PipelineSteps = {
  __typename?: 'PipelineSteps';
  name: Scalars['String']['output'];
  type: Scalars['String']['output'];
  prompt?: Maybe<Scalars['String']['output']>;
  command?: Maybe<Scalars['String']['output']>;
};

export type Pipeline = Node & Document & {
  __typename?: 'Pipeline';
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  trigger?: Maybe<Scalars['String']['output']>;
  steps?: Maybe<Array<Maybe<PipelineSteps>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PipelineStepsFilter = {
  name?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  prompt?: InputMaybe<StringFilter>;
  command?: InputMaybe<StringFilter>;
};

export type PipelineFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  trigger?: InputMaybe<StringFilter>;
  steps?: InputMaybe<PipelineStepsFilter>;
};

export type PipelineConnectionEdges = {
  __typename?: 'PipelineConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pipeline>;
};

export type PipelineConnection = Connection & {
  __typename?: 'PipelineConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PipelineConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateContext: Context;
  createContext: Context;
  updatePipeline: Pipeline;
  createPipeline: Pipeline;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateContextArgs = {
  relativePath: Scalars['String']['input'];
  params: ContextMutation;
};


export type MutationCreateContextArgs = {
  relativePath: Scalars['String']['input'];
  params: ContextMutation;
};


export type MutationUpdatePipelineArgs = {
  relativePath: Scalars['String']['input'];
  params: PipelineMutation;
};


export type MutationCreatePipelineArgs = {
  relativePath: Scalars['String']['input'];
  params: PipelineMutation;
};

export type DocumentUpdateMutation = {
  context?: InputMaybe<ContextMutation>;
  pipeline?: InputMaybe<PipelineMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  context?: InputMaybe<ContextMutation>;
  pipeline?: InputMaybe<PipelineMutation>;
};

export type ContextMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PipelineStepsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  prompt?: InputMaybe<Scalars['String']['input']>;
  command?: InputMaybe<Scalars['String']['input']>;
};

export type PipelineMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  trigger?: InputMaybe<Scalars['String']['input']>;
  steps?: InputMaybe<Array<InputMaybe<PipelineStepsMutation>>>;
};

export type ContextPartsFragment = { __typename: 'Context', title: string, description?: string | null, body?: any | null };

export type PipelinePartsFragment = { __typename: 'Pipeline', name: string, description?: string | null, trigger?: string | null, steps?: Array<{ __typename: 'PipelineSteps', name: string, type: string, prompt?: string | null, command?: string | null } | null> | null };

export type ContextQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContextQuery = { __typename?: 'Query', context: { __typename: 'Context', id: string, title: string, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContextConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContextFilter>;
}>;


export type ContextConnectionQuery = { __typename?: 'Query', contextConnection: { __typename?: 'ContextConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContextConnectionEdges', cursor: string, node?: { __typename: 'Context', id: string, title: string, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PipelineQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PipelineQuery = { __typename?: 'Query', pipeline: { __typename: 'Pipeline', id: string, name: string, description?: string | null, trigger?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, steps?: Array<{ __typename: 'PipelineSteps', name: string, type: string, prompt?: string | null, command?: string | null } | null> | null } };

export type PipelineConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PipelineFilter>;
}>;


export type PipelineConnectionQuery = { __typename?: 'Query', pipelineConnection: { __typename?: 'PipelineConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PipelineConnectionEdges', cursor: string, node?: { __typename: 'Pipeline', id: string, name: string, description?: string | null, trigger?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, steps?: Array<{ __typename: 'PipelineSteps', name: string, type: string, prompt?: string | null, command?: string | null } | null> | null } | null } | null> | null } };

export const ContextPartsFragmentDoc = gql`
    fragment ContextParts on Context {
  __typename
  title
  description
  body
}
    `;
export const PipelinePartsFragmentDoc = gql`
    fragment PipelineParts on Pipeline {
  __typename
  name
  description
  trigger
  steps {
    __typename
    name
    type
    prompt
    command
  }
}
    `;
export const ContextDocument = gql`
    query context($relativePath: String!) {
  context(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContextParts
  }
}
    ${ContextPartsFragmentDoc}`;
export const ContextConnectionDocument = gql`
    query contextConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContextFilter) {
  contextConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContextParts
      }
    }
  }
}
    ${ContextPartsFragmentDoc}`;
export const PipelineDocument = gql`
    query pipeline($relativePath: String!) {
  pipeline(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PipelineParts
  }
}
    ${PipelinePartsFragmentDoc}`;
export const PipelineConnectionDocument = gql`
    query pipelineConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PipelineFilter) {
  pipelineConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PipelineParts
      }
    }
  }
}
    ${PipelinePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      context(variables: ContextQueryVariables, options?: C): Promise<{data: ContextQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContextQueryVariables, query: string}> {
        return requester<{data: ContextQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContextQueryVariables, query: string}, ContextQueryVariables>(ContextDocument, variables, options);
      },
    contextConnection(variables?: ContextConnectionQueryVariables, options?: C): Promise<{data: ContextConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContextConnectionQueryVariables, query: string}> {
        return requester<{data: ContextConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContextConnectionQueryVariables, query: string}, ContextConnectionQueryVariables>(ContextConnectionDocument, variables, options);
      },
    pipeline(variables: PipelineQueryVariables, options?: C): Promise<{data: PipelineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PipelineQueryVariables, query: string}> {
        return requester<{data: PipelineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PipelineQueryVariables, query: string}, PipelineQueryVariables>(PipelineDocument, variables, options);
      },
    pipelineConnection(variables?: PipelineConnectionQueryVariables, options?: C): Promise<{data: PipelineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PipelineConnectionQueryVariables, query: string}> {
        return requester<{data: PipelineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PipelineConnectionQueryVariables, query: string}, PipelineConnectionQueryVariables>(PipelineConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  